MONIT-26428 - Support OTLP Summary metrics
thepeterstone/wavefront-proxy pull request #5
Opened 2022-04-07 20:50 UTC by thepeterstone

2022-04-08 00:00 UTC, keep94 reviewed
Here are some comments. More to come later.

2022-04-08 00:21 UTC, keep94 requested changes
Looks good. Do we want the WF proxy to work exactly like the metrics exporter?  If so, we will want to handle pre-existing tags named "quantile" See my specific comments.

2022-04-08 00:21 UTC, keep94 commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpTestHelpers.java
> +  public static io.opentelemetry.proto.metrics.v1.Metric.Builder otlpSummaryGenerator(SummaryDataPoint point) {
Should this have a javadoc since it is a public method? but I see that the existing public methods in this class don't have javadocs either.

2022-04-08 00:21 UTC, keep94 commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpProtobufUtilsTest.java
> +    assertAllPointsEqual(expectedPoints, transformedPoints);
I'm curious why in the simpleSummary test, easy mock is used whereas this test doesn't use mocks?  I prefer this style of test over ones with easy mock because a test like this is much easier to follow.

2022-04-08 00:21 UTC, keep94 commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpMetricsTest.java
> +    long epochTime = 1515151515L;
It might be worth adding some pre-existing tags to test that they persist. In particular, be sure to test what happens if there is a pre-existing tag named "quantile".  It should be renamed to "_quantile" to make room for the actual "quantile" you are adding.

2022-04-11 18:45 UTC, oppegard approved these changes
We paired on this - lgtm.

2022-04-11 18:47 UTC, oppegard commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpTestHelpers.java
> +  public static io.opentelemetry.proto.metrics.v1.Metric.Builder otlpSummaryGenerator(SummaryDataPoint point) {
I don't think there's consistency in making javadocs. It's probably appreciated, but not enforced. The maintainer of the proxy, @laullon, might have a different viewpoint.

2022-04-12 09:41 UTC, laullon commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpTestHelpers.java
> +  public static io.opentelemetry.proto.metrics.v1.Metric.Builder otlpSummaryGenerator(SummaryDataPoint point) {
This is a test, so no need...

2022-04-12 16:50 UTC, thepeterstone commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpMetricsTest.java
> +        .setTimeUnixNano(TimeUnit.SECONDS.toNanos(epochTime)).build();
I tend to think the method name `setTimeUnixNano` is self-documenting as to the units, but if it's confusing we could add a comment or extract a named variable to clarify.

2022-04-12 16:50 UTC, thepeterstone commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +      attributes.add(quantileTag);
Ah, good point. I'll add that.

2022-04-12 16:52 UTC, thepeterstone commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpProtobufUtilsTest.java
> +    assertAllPointsEqual(expectedPoints, transformedPoints);
The `simpleSummary` test in OtlpMetricsTest is more of an integration test, making sure summaries pass through the system. The unit tests in this class are more focused on individual requirements, so they don't mock components.

2022-04-12 16:55 UTC, thepeterstone commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpMetricsTest.java
> +    long epochTime = 1515151515L;
The `quantile`/`_quantile` tag handling will want a unit test. I'll look at whether it makes sense to add a tag here for end-to-end verification.

2022-04-12 23:15 UTC, thepeterstone commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +      attributes.add(quantileTag);
Added in [e00163e](https://github.com/thepeterstone/wavefront-proxy/pull/5/commits/e00163e32a27ea4b3b1b180b8316ad5586e83a7e)

2022-04-19 08:07 UTC, laullon approved these changes
LGTM

2022-04-19 16:54 UTC, keep94 requested changes

2022-04-19 16:54 UTC, keep94 commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +    if (pointAttributes.isEmpty()) return pointAttributes;
IMO I'd get rid of this if statement.  In general you return a new list which is good, but in this special case, you return the same list passed in if it is empty. This can cause weirdness if the caller later adds elements to pointAttributes because then the returned list suddenly gets these new elements because it is the same list.

2022-04-19 17:04 UTC, thepeterstone commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +    if (pointAttributes.isEmpty()) return pointAttributes;
I see your point, but this method is private and the results are used to create a new list (via `Collectors.toList` and `new ArrayList<>()`) so I think that would be a superfluous allocation.

2022-04-19 17:55 UTC, keep94 approved these changes

2022-04-19 17:55 UTC, keep94 commented
LGTM

2022-04-25 23:23 UTC, merged