MONIT-26425-Proxy understands OTLP Cumulative Histograms
thepeterstone/wavefront-proxy pull request #8
Opened 2022-04-30 00:07 UTC by deosu

2022-05-03 16:55 UTC, oppegard commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtilsTest.java
> +        .addAttributes(KeyValue.newBuilder().setKey("le").setValue(AnyValue.newBuilder()
there's a helper, `OtlpTestHelpers.attribute("le", "someVal")`, to build a `KeyValue` for you.

2022-05-03 16:55 UTC, oppegard commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtilsTest.java
> +    // bucket = 1, datapoint in bucket: 1
delete me

2022-05-03 16:55 UTC, oppegard commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtilsTest.java
> +    Histogram histo = Histogram.newBuilder()
delete me

2022-05-03 16:55 UTC, oppegard commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtilsTest.java
> +    // bucket = 1, datapoint in bucket: 1
delete me

2022-05-03 16:56 UTC, oppegard commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtilsTest.java
> +    // bucket = 1, datapoint in bucket: 1
delete me

2022-05-03 16:56 UTC, oppegard commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +//            "temporality " + histogram.getAggregationTemporality().name());
Uncomment me.

2022-05-03 16:56 UTC, oppegard commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +
delete me

2022-05-03 17:01 UTC, keep94 requested changes

2022-05-03 17:52 UTC, deosu commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +
done

2022-05-03 17:53 UTC, deosu commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +    } else if (otlpMetric.hasHistogram()) {
this was done to avoid setting up a source and preprocessing of rules in each of the methods.

2022-05-03 17:53 UTC, deosu commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +//            "temporality " + histogram.getAggregationTemporality().name());
done

2022-05-03 18:01 UTC, deosu commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +      reportPoints.addAll(transformHistogramDataPoint(name, point, resourceAttrs));
The reason we are not passing the `reportPoints` as an input parameter is to keep all the transform methods consistent. But, it is a good suggestion. If we want to take this suggestion then I think we should update all the transform methods(for Sum, Summary, etc). @oppegard what are your thoughts on this?

2022-05-03 18:10 UTC, deosu commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +      ReportPoint rp = pointWithAnnotations(name, point.getAttributesList(), resourceAttrs,
Unit tests are failing post this implementation(reverted the changes). We have to create a new builder every time as the annotations are getting appended after each iteration.

2022-05-03 18:18 UTC, deosu commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtilsTest.java
> +    // bucket = 1, datapoint in bucket: 1
done

2022-05-03 18:18 UTC, deosu commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtilsTest.java
> +    // bucket = 1, datapoint in bucket: 1
done

2022-05-03 18:18 UTC, deosu commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtilsTest.java
> +    Histogram histo = Histogram.newBuilder()
done

2022-05-03 18:19 UTC, oppegard commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +      reportPoints.addAll(transformHistogramDataPoint(name, point, resourceAttrs));
I think this is an optimization that we shouldn't worry about until we have data suggesting we're allocating too many objects. I'm pretty sure the JVM is highly optimized to handle these kinds of situations – it shouldn't be making duplicate copies of the `ReportPoint` objects. There will be a couple wrappers of `List<ReportPoint>` that points to the same `ReportPoint` objects, but that's it.

2022-05-03 18:20 UTC, deosu commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtilsTest.java
> +        .addAttributes(KeyValue.newBuilder().setKey("le").setValue(AnyValue.newBuilder()
Thank you. Fixed.

2022-05-03 18:21 UTC, deosu commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtilsTest.java
> +    // bucket = 1, datapoint in bucket: 1
done

2022-05-03 18:22 UTC, oppegard commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +      reportPoints.addAll(transformHistogramDataPoint(name, point, resourceAttrs));
https://stackoverflow.com/questions/7924887/will-addall-function-in-java-make-a-copy

2022-05-03 23:46 UTC, keep94 commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpMetricsTest.java
> +
Should we test that existing "le" tags get moved to "_le"?

2022-05-03 23:47 UTC, keep94 approved these changes

2022-05-04 16:42 UTC, deosu commented on proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpProtobufPointUtils.java
> +      reportPoints.addAll(transformHistogramDataPoint(name, point, resourceAttrs));
sounds good

2022-05-04 16:43 UTC, deosu commented on proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpMetricsTest.java
> +
We already have a unit test for this edge case.

2022-05-04 17:12 UTC, oppegard approved these changes
LGTM

2022-05-05 17:37 UTC, merged